// src/utils/constants.js
export const DATABASE_ID = import.meta.env.VITE_REACT_APP_APPWRITE_DATABASE_ID;
export const POSTS_COLLECTION_ID = import.meta.env.VITE_REACT_APP_APPWRITE_POSTS_COLLECTION_ID;
export const COMMENTS_COLLECTION_ID = import.meta.env.VITE_REACT_APP_APPWRITE_COMMENTS_COLLECTION_ID;
